import FWCore.ParameterSet.Config as cms

from Validation.MtdValidation.btlSimHitsPostProcessor_cfi import btlSimHitsPostProcessor
from Validation.MtdValidation.btlLocalRecoPostProcessor_cfi import btlLocalRecoPostProcessor
from Validation.MtdValidation.MtdTracksPostProcessor_cfi import MtdTracksPostProcessor
from Validation.MtdValidation.Primary4DVertexPostProcessor_cfi import Primary4DVertexPostProcessor
from Validation.MtdValidation.btlTimeMonitoringPostProcessor_cfi import btlTimeMonitoringPostProcessor

mtdValidationPostProcessor = cms.Sequence(btlSimHitsPostProcessor + btlLocalRecoPostProcessor + MtdTracksPostProcessor + Primary4DVertexPostProcessori + btlTimeMonitoringPostProcessor)
